---
title: "Class Notes Web Scraping"
author: "Richard Ressler"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(rvest)
```

```{r}
html_obj <- read_html("https://www.imdb.com/list/ls055592025/")
class(html_obj)
```

```{r}
ranking_elements <- html_nodes(html_obj, css=".lister-item-header a , .text-primary")
ranking_text <- html_text(ranking_elements)
head(ranking_text)
length(ranking_text)
ranking_text
```
```{r}

tibble(text = rankig_text) %>% 
  mutate(rownum = row_number(),
         iseven = rownum %% 2 ==0,
         movie = rep(1:100, each = 2)) %>% 
  select(-rownum) %>% 
  pivot_wider(names_from = iseven, values_from = text) %>% 
  select(-movie, "Rank" = "FALSE", movie = "TRUE") %>% 
  mutate(Rank = parse_number(Rank)) ->
  movierank
  head(movierank)
```

Get Directors adn FIlm Names

```{r}
dirdat <- html_nodes(html_obj, css = ".text-small a:nth-child(1)")
dirdat <- html_text(dirdat)
head(dirdat)
length(dirdat)
dirdat <- dirdat[-1]
head(dirdat)

filmdat <- html_nodes(html_obj, css = ".lister-item-header a")
filmdat <- html_text(filmdat)
length(filmdat)

tibble(film = filmdat, director = dirdat)
data.frame(film = filmdat, director = dirdat)
```

bigger example
```{r}
dataobj <- html_nodes(html_obj, css = ".favorable , .genre , .unbold , .lister-item-header a")
datatext <- html_text(dataobj)
view(datatext)

```

```{r}
datadf <- tibble(text = datatext)
```


```{r}
datadf %>% 
  mutate(ismovierank = str_detect(text, "^\\d+\\.$")) ->
  datadf
slice(datadf, 132:140)

datadf %>% 
  mutate(movienum = cumsum(ismovierank)) %>% 
  filter(movienum > 0) ->
  datadf
head(datadf)

movierank$movie
datadf %>% 
  mutate(isname = text %in% movierank$movie)->
  datadf
head(datadf)

datadf %>% 
  mutate(isyear = str_detect(text, "\\(\\d+\\)")) ->
  datadf
head(datadf, 12)

datadf %>% 
  mutate(isgenre = str_detect(text, "^\\n"))->
  datadf
head(datadf,12)

datadf %>% 
  group_by(ismovierank, isname, isyear, isgenre) %>% 
  count()

datadf %>% 
  mutate(ismeta = !ismovierank & !isname & !isyear & !isgenre)->
  datadf
head(datadf, 12)
```

```{r}
datadf %>% 
  mutate(key = case_when(ismovierank ~ "rank",
                       isname ~ "name",
                       isyear ~ "year",
                       isgenre ~"genre",
                       ismeta ~ "meta")) %>% 
  select(key, text, movienum) %>% 
  pivot_wider(names_from = key, values_from = text) ->
  data_wide
head(data_wide)
```

```{r}
data_wide %>% 
  mutate(genre = str_replace_all(genre, "\\n", ""),
         genre = str_squish(genre),
         meta = parse_number(meta),
         rank = parse_number(rank),
         year = parse_number(year),
         movienum=NULL) ->
  data_wide
head(data_wide)

```

Scraping Tables
```{r}
wikixml <- read_html("https://en.wikipedia.org/wiki/Atlantic_hurricane_season")
```

```{r}
wikidat <- html_nodes(wikixml, "table")
tablist <- html_table(wikidat, fill = TRUE)
length(tablist)
tablist[[4]]
```

```{r}
mosque <- read_html("https://en.wikipedia.org/wiki/List_of_the_oldest_mosques")
```

```{r}
headers <- html_text(html_nodes(mosque, css = "caption ,  #Mentioned_in_the_Quran"))

tabnode <- html_nodes(mosque, css = "table.wikitable")
tablist <- html_table(tabnode, fill = TRUE)
length(tablist)
length(headers)
headers
#view(tablist)
```

CHeck the names in each table in the list

```{r}
tab_names <- map(tablist, names)

(tab_names)

```

Fix 18 without  a country

```{r}
tablist[[18]] %>% 
  mutate(Country = "Russia") ->
  tablist[[18]]
tab_names <- map(tablist, names)

(tab_names)
```
13 has an extra column

```{r}
names(tablist[[13]])[ncol(tablist[[13]])] <- "blah"
tab_names <- map(tablist, names)

(tab_names)
```

Select Variables of interest

```{r}
map(tablist, ~select(., Building, Country, fb = "First built")) ->
tablist
str(tablist)
```


Replace Century Dates with last year of the century

```{r}
head(tablist[[5]])
map(tablist, ~mutate(., fb = str_replace(fb, "th", "00"))) %>% 
  map(., ~mutate(., fb = str_extract(fb, "^\\d+"))) ->
  tablist
tablist[[5]]
```
Clean the headers
```{r}
#head(headers)
str_replace_all(headers, "\\n", "") %>% 
  str_replace_all("\\(.+\\)", "") -> 
  headers
```

Add the header information to each table in the list

```{r}
for (index in seq_along(tablist)){
  mutate(tablist[[index]], category = headers[[index]])->
    tablist[[index]]
}
tablist[[5]]
```

merge teh tables together
```{r}
bind_rows(tablist) ->
  tabdf
head(tabdf, 15)
```

