---
title: "Class Notes week 7"
author: "Richard Ressler"
date: "3/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)
```

```{r}
library(shiny)

ui <- fluidPage(
  textInput("name", "What's your name?"),
  passwordInput("password", "What's your password?"),
  textAreaInput("story", "Tell me about yourself")
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

```{r}
library(shiny)

ui <- fluidPage(
  numericInput("num", "Number one", value = 0, min = 0, max = 100),
  sliderInput("num2", "Number two", value = 50, min = 0, max = 100),
  sliderInput("rng", "Range", value = c(10, 20), min = 0, max = 100)
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)

ui <- fluidPage(
  dateInput("dob", "When were you born?"),
  dateRangeInput("holiday", "When do you want to go on vacation next?")
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)

weekdays <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
ui <- fluidPage(
  selectInput("state", "Where do you live?", choices = state.name),
  radioButtons("weekday", "What's your favorite day of the week?", choices = weekdays),
  checkboxGroupInput("weekday2", "What days do you work?", choices = weekdays)
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  varSelectInput("carcol", "Which Column?", data = mtcars, selected = "cyl")
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  checkboxInput("startrek", "Like Star Trek?")
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  fileInput("filenames", "Which Files", multiple = FALSE)
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  actionButton("click", "Click me!"),
  actionLink("Link", "No, click me!")
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)

ui <- fluidPage(
  textOutput("text"),
  verbatimTextOutput("code")
)

server <- function(input, output, session) {
  output$text <- renderText({
    "Hello World!"
  })

  output$code <- renderPrint({
    summary(c(1, 2, 3, 4))
  })
}

shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)

ui <- fluidPage(
  tableOutput("static")
)

server <- function(input, output, session) {
  output$static <- renderTable({
    head(mtcars)
    })
}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  dataTableOutput("dynamic")
)

server <- function(input, output, session) {
  output$dynamic <- renderDataTable({ mtcars }, options = list(pageLength = 5))
}

shinyApp(ui = ui, server = server)
```

```{r}

```
```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  plotOutput("plot", height = "300px", width = "500px")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    ggplot(mpg, aes(x = displ, y = hwy)) +
      geom_point() +
      theme_bw() +
      xlab("Displacement") +
      ylab("Highway MPG")
    })
}

shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  varSelectInput("var1", "Pick the X variable", data = mtcars),
  varSelectInput("var2", "Pick the Y variable", data = mtcars, selected = "hp"),
  radioButtons("color", "What color do you want", 
               choiceNames = c("Red", "Blue"),
               choiceValues = c("red", "blue")),
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    ggplot(mtcars, aes(x = !!input$var1, y = !!input$var2))+
      geom_point(color = input$color)+
      ggtitle("My Plot")
    
  })
}

shinyApp(ui, server)
```

```{r}
library(shiny)

ui <- fluidPage(
  textInput("text", "What Text", value = "Default Text")
)

server <- function(input, output) {
  paste("The value text is", input$text) ## Don't do this!
}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  textInput("name", "What is your name?"),
  textOutput("greetname")
  
)

server <- function(input, output, session) {
  output$greetname <- renderText({
    paste("Hello, ", input$name)
  })
}

shinyApp(ui, server)
```

```{r}
library(shiny)
library(stringr)

ui <- fluidPage(
  textInput("text", "What Text?", value = "dog"),
  textOutput("pigtext1"),
  textOutput("pigtext2")
)

server <- function(input, output) {

  x <- reactive({
    str_replace(input$text, "([^aeiouAEIOU]*)(.*)", "\\2\\1ay")
    })
  output$pigtext1 <- renderText(x())
  output$pigtext2 <- renderText(x())
}

shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)
library(tidyverse)
library(broom)

ui <- fluidPage(
  numericInput("nsamp", "Number of samples", value = 50, step = 1),
  numericInput("diff", "Effect size", value = 0.5, step = 0.1),
  plotOutput("plot"),
  verbatimTextOutput("text")
)

server <- function(input, output) {
  x1 <- reactive({
    rnorm(n = input$nsamp, mean = 0, sd = 1)
  })

  x2 <- reactive({
    rnorm(n = input$nsamp, mean = input$diff, sd = 1)
  })

  output$plot <- renderPlot({
    data.frame(`1` = x1(), `2` = x2()) %>%
      pivot_longer(cols = everything(),names_to = "Group", values_to = "y") %>%
      ggplot(aes(x = Group, y = y)) +
      geom_boxplot() +
      theme_bw()
  })

  output$text <- renderPrint({
    t.test(x1(), x2()) %>%
      tidy() %>%
      select(estimate, `P-value` = p.value, Lower = conf.low, Higher = conf.high)
  })
}

shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)
library(shinythemes)
library(fresh)
library(ggplot2)

create_theme(
  theme = "default",
  bs_vars_color(
    gray_base = "#354e5c"
  ),
  bs_vars_wells(
    bg = "#90ee90",
    border = "#552D42"
  ),
  bs_vars_global(
    body_bg = "#e5ffe5"
  ),
  bs_vars_input(
    color = "#5d3954",
    border_radius="20px"
  ),
  #
  output_file = "www/mytheme.css"
)

ui <- fluidPage(
  theme = "mytheme.css",
  titlePanel("Old Faithful Geyser Data"),
  sidebarLayout(
    sidebarPanel(
     wellPanel("This is a well Panel",
      textInput("plot_title", "Plot Title?", value = "Your Title"),
       sliderInput("bins",
                  "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
     )
       ),
    mainPanel(
      plotOutput("distPlot")
    )
  )
)

server <- function(input, output) {
  output$distPlot <- renderPlot({
    ggplot(faithful, aes(x = waiting)) +
      geom_histogram(bins = input$bins, fill = "palegreen4") +
      theme(plot.background = element_rect(fill = "palegreen1"))+
      ggtitle(input$plot_title) +
      theme(
        panel.background = element_rect(fill = "palegreen1",
                                        colour = "palegreen1",
                                        size = 0.5, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                        colour = "white"),
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                        colour = "white")
      )
  })
}

shinyApp(ui = ui, server = server)
```
```{r}
tags$a("Click Me!", href = "https://www.youtube.com/watch?v=dQw4w9WgXcQ")
```

