---
title: "Class File"
author: "Richard Ressler"
date: "2/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
suppressMessages(library(tidyverse))

```

```{r}
f02 <- function(x, y) {
  # A comment
  x + y
}
formals(f02)
body(f02)
environment(f02)
```
```{r}
formals(99)
formals(sum)
body(sum)
formals(ggplot)
body(ggplot)
environment(ggplot)
```
```{r}
f01 <- function(x) {
  sin(1 / x ^ 2)
}
f01(2)
map(mtcars, function(x) length(unique(x))) 
```

```{r}
sum(exp(c(1,2,5)))
x <- c(1,2,5)
exp_x <- exp(x)
sum_ex <- sum(exp_x)
sum_ex
c(1,2,5) %>% 
  exp() %>% 
  sum()
```
# Name Masking
```{r}
x <- 10
y <- 20
g02 <- function(){
  x <- 1
  y <- 2
  c(x,y)
}
g02()
c(x,y)
```

```{r}
x <- 30
g04 <- function() {
  y <- 2
  i <- function() {
    z <- 1
    c(x, y, z)
  }
  i()
}
g04()
```

```{r}
g07 <- function(x) x + 1
g08 <- function() {
  g07 <- function(x) x + 100
  g07(10)
}
g08()
```
```{r}
g11 <- function() {
  if (!exists("a")) {
    a <- 1
  } else {
    a <- a + 1
  }
  a
}

g11()
```

```{r}
g12 <- function() x + 1
x <- 15
g12()
codetools::findGlobals(g12)
x <- 4
environment(g12) <- emptyenv()
g12()
```

```{r}
f <- function(x) {
  f <- function(x) {
    f <- function() {
      x ^ 2
    }
    f() + 1
  }
  f(x) * 2
}
f(10)
```
# Lazy Evaluation
```{r}
h01 <- function(x) {
    10
}
h01(stop("This is an error!"))
```

```{r}
y <- 10
h02 <- function(x) {
  y <- 100
  x + 1
}

h02(y)
h02(y <- 1000)
y
```
```{r}
double <- function(x) { 
  message("Calculating...")
  x * 2
}

h03 <- function(x) {
  c(x, x)
}

h03(double(20))
```
```{r}
h04 <- function(x = 2, y = x * 2, z = a + b) {
  a <- 10
  b <- 100
  c(x, y, z)
}

h04()
```

```{r}
h05 <- function(x = ls()) {
  a <- 1
  x
}

ls()
h05()
h05(ls())
```

```{r}
h06 <- function(x = 10) {
  list(missing(x), x)
}
str(h06())
str(h06(10))
```

```{r}
j01 <- function(x) {
  if (x < 10) {
    return(0)
  } else {
    return(10)
  }
}
j01(5)
```
```{r}
j03 <- function() invisible(1)
(j03())
(x <- 4)
a <- b <- c <- d <- 4
a
b
c
d

```

```{r}
library(searcher)
# Using the generic search error handler
log(-1)
#search_stackoverflow("NaNs produced")
#search_duckduckgo("NaNs produced")
#options(error = searcher("google"))
z <- list(1,2,tribble(x=2, y=c(5,2,3)))
options(error = NULL)
```
```{r}
library(errorist)
```

```{r}
enable_errorist()
z <- list(1,2,tribble(x=2, y=c(5,2,3)))
```

```{r}
#detach("package:errorist", unload = TRUE)
enable_errorist()
disable_errorist()
z <- list(1,2,tribble(x=2, y=c(5,2,3)))
```

```{r}
z <- list(1,2,tribble(x=2, y=c(5,2,3)))
```

```{r}
f <- function(a) g(a)
g <- function(b) h(b)
h <- function(c) i(c)
i <- function(d) {
  if (!is.numeric(d)) {
    stop("`d` must be numeric", call. = FALSE)
  }
  d + 10
}
f("a")
```

```{r}
g <- function(b) {
  browser()
  h(b)
}
f(10)
```

```{r}
g <- function(b) {
  if (b < 0) {
    browser()
  }
  h(b)
}

```

```{r}
library(devtools)
has_devel()
```
```{r}
library(available)

available("myfp")
```

