---
title: "Untitled"
author: "Richard Ressler"
date: "1/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
car <- "0"
class(car)

x <- c("i", "am", "a", "string", "vector")
x[2:3]
x <- " As Tolkein said, \"Not all those who \nwander are lost\""
x
writeLines(x)

print(x)
library(tidyverse)
```

```{r}
str_length((x <- "upon the hearth \nthe fire is red,"))

print(x)
writeLines(x)
str_length(print(x))
str_length(factor("abc"))
```
```{r}
x <- "Faithless is he that says"
y <- "farewell when the road darkens"
x
y
str_c(x,y, sep = " ")
```
```{r}
x <- c("short", "Cuts", "make", "long", "delays", sep = " ")
str_c(x,"LOTR",  collapse = " ")
str_c(x, NA)
```

```{r}
x <- "The Road \ngoes ever on and on"
str_sub(x, start = 2, end = 16)

str_sub(x, start = 2, end = 6) <- "Tolkien"
x
```


```{r}
w <- "But under a tall tree"
x <- "FRELL I will lie"
y <- "And let the clouds go"
z <- "sailing by"

line1 <- str_c(w, str_sub(x, 7, str_length(x)), sep = " ")
line2 <- str_c("\n", y)
line2
lines1_2 <- str_c(line1, line2)

lines1_2
writeLines(lines1_2)
```
Regular Expressions

```{r}
x <- "Ho! Ho! Ho! to the bottle I go to heal my \\heart and drown my woe."
str_replace_all(x, "\\\\", "XX")
```

Anchoring

```{r}
x <- c("But", "under", "a", "tall", "treat", "i", "will", "lie")
x
str_replace(x, "^t...t$", "XX")
```

```{r}
x <- c("apple", "barn", "ape", "apes", "cart", "alas", "pain", "ally")
x
str_replace(x, "^a...$", "foo")
```

Specioal Characters

```{r}
x <- c("Abba: 555-1234", "Anna: 555-0987", "Andy: 555-7654")

str_replace(x, "\\d\\d\\d-\\d\\d\\d\\d", "XXX-XXXX")

str_replace(x, "\\s", "X")

#[^abc]

str_replace(x, "A[bn][bn]a","X" )

str_replace(x, "A[^b]", "XXXX")

# | 
#
str_replace(x, "(?i)an(na|dy)", "XXXX")
```

```{r}
library(lubridate)
```

```{r}
class(today())
class(now())
hms::as_hms(now())

x <- parse_date("10/11/2020", format = "%m/%d/%Y")
class(x)

y <- parse_datetime("10/11/2020 11:59:20", format = "%m/%d/%Y %H:%M:%S")
class(y)
z <- parse_time("11:59:20", "%H:%M:%S")
class(z)
```

```{r}
help(ymd)
```

```{r}
ymd(c("2011/01-10", "2011-01/10", "20110110"))

hms(c("10:40:10", "10 40 10"))
```

```{r}
mdy_hms("05/26/2004 UTC 11:11:11.444")

parse_datetime("26 2004 05 UTC 11/11/11.444", "%d %Y %m UTC %H/%M/%S")
```

```{r}
d1 <- "January 1, 2010"
d2 <- "2015-Mar-07"
d3 <- "06-Jun-2017"
d4 <- c("August 19 (2015)", "July 1 (2015)")
d5 <- "12/30/14" # Dec 30, 2014 

mdy(d1)
ymd(d2)
dmy(d3)
mdy(d4)
mdy(d5)
```
```{r}
make_date(year = 1981, month = 6, day = 25)
make_datetime(year = 1972, month = 2, day = 22, hour = 10, min = 9, sec = 01)
```

```{r}
library(nycflights13)
data("flights")
head(flights)
```

```{r}
flights %>% 
  mutate(datetime = make_datetime(year = year,
                                  month = month,
                                  day = day,
                                  hour = hour,
                                  min = minute)) ->
  flights
select(flights, datetime)
ggplot(flights, aes(x=datetime)) +
  geom_freqpoly(bins = 365)
```

```{r}
flights %>% 
  filter(as_date(datetime) == ymd(20130704)) %>% 
  ggplot(aes(x=datetime)) +
  geom_freqpoly(binwidth = 600)
```

```{r}
fake <- tribble(~year, ~month, ~day, ~month_num,
                ##----/-------/----------------
                2018,  "Oct",  1,    10,
                2011,  "Nov",  2,    11,
                2019,  "Dec",  3,    12,
                2010,  "JAN",  5,     1,
                1999,  "MAr",  1,     3,
                1987,  "ApR",  3,     4,
                2020,  "maY",  2,     5,
                2010,  "May",  4,     5) 


str(fake)

fake %>% 
  mutate(datetime = make_datetime(year = year, month=month_num, 
                                  day = day)) %>% 
  filter(datetime > ymd("20100201"))
```


```{r}
fake %>% 
  mutate(month = str_to_sentence(month),
         month = parse_factor(month, levels = month.abb),
         month = as.numeric(month),
         date = make_date(year = year, month = month, day = day)) %>% 
  filter(date > ymd(20100201))
  
  
 
```

```{r}
ddat <- mdy_hms("01/02/1970 03:51:44")
class(ddat)

month(ddat, label = TRUE)
yday(ddat)
minute(ddat)
```

\
```{r}
wmata <- read_csv("https://dcgerard.github.io/stat_412_612/data/wmata_ridership.csv")
head(wmata)

```
```{r}
wmata %>% 
  mutate(year = year(Date),
         month = month(Date),
         day = wday(Date, label = TRUE)) %>% 
  filter(year != 2004) %>% 
  group_by(year, month) %>% 
  mutate(prop = Total/sum(Total)) %>% 
  ungroup() %>% 
  ggplot(aes(x=day, y = prop)) +
  geom_boxplot() +
  theme_bw()
```
```{r}
ddat <- mdy_hms("01/04/1970 12:30:00")
 round_date(ddat, unit = "hour")
 ddat <- mdy_hms("02/14/1970 12:00:00")
 round_date(ddat, unit = "day")
```

```{r}
ymd(19800128) + months(1)
ymd(19800131) + months(1)
OlsonNames()
```

