---
title: "Class Notes Tidy Text part 2"
author: "Richard Ressler"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(janeaustenr)
```

```{r}
austen_books() %>% 
  unnest_tokens(word, text) %>%
  mutate(word = str_extract(word, "[a-z']+")) %>%
  count(book, word, sort = TRUE) ->
  book_words 


book_words %>% 
  group_by(book) %>% 
  summarize(total = sum(n)) ->
  total_words 

book_words %>% 
  left_join(total_words) ->
  book_words

book_words
```
```{r}
book_words %>% 
  ggplot(aes(n/total, fill = book)) +
  geom_histogram(show.legend = FALSE) +
  xlim(NA, .0009)+
  facet_wrap(~book, ncol = 2, scales = "free")
```

```{r}
book_words %>% 
  filter(n ==1) %>% 
  nrow()
```

```{r}
book_words %>% 
  group_by(book) %>% 
  mutate(rank = row_number(), 
         term_frequency = n/total) ->
  freq_by_rank

freq_by_rank
```

```{r}
freq_by_rank %>% 
  ggplot(aes(rank, term_frequency, color = book)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
```

```{r}
freq_by_rank %>% 
  filter(rank < 500, rank > 10) ->
  rank_subset

lmout <-  lm(log10(term_frequency) ~ log10(rank), data = rank_subset)
broom::tidy(lmout)[c(1,2,5)]
```

```{r}
freq_by_rank %>% 
  ggplot(aes(rank, term_frequency, color = book)) + 
  geom_abline(intercept = -0.62, slope = -1.1, color = "red", linetype = 2) +
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
```

```{r}
book_words %>% bind_tf_idf(word, book, n) ->
  book_words
book_words
```

```{r}
book_words %>%
  select(-total) %>%
  arrange(desc(tf_idf))
```

```{r}
book_words %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  group_by(book) %>% 
  top_n(10) %>% 
  ungroup() %>%
  ggplot(aes(word, tf_idf, fill = book)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~book, ncol = 2, scales = "free") +
  coord_flip()
```

# Physics Texts
```{r}
library(gutenbergr)
physics <- gutenberg_download(c(37729, 14725, 13476, 30155), meta_fields = "author") 
physics %>%
  unnest_tokens(word, text) %>%
  mutate(word = str_extract(word, "[a-z']+")) %>%
  count(author, word, sort = TRUE) ->
  physics_words 

physics_words  
```

```{r}
physics_words %>%
  bind_tf_idf(word, author, n) %>%
  mutate(word = fct_reorder(word, tf_idf)) %>%
  mutate(author = factor(author, levels = c("Galilei, Galileo",
                                            "Huygens, Christiaan", 
                                            "Tesla, Nikola",
                                            "Einstein, Albert"))) ->
  physics_plot
```
```{r}
    physics_plot %>% 
      group_by(author) %>% 
      top_n(15, tf_idf) %>% 
      ungroup() %>%
      mutate(word = reorder(word, tf_idf)) %>%
      ggplot(aes(word, tf_idf, fill = author)) +
      geom_col(show.legend = FALSE) +
      labs(x = NULL, y = "tf-idf") +
      facet_wrap(~author, ncol = 2, scales = "free") +
      coord_flip()
```

```{r}
physics %>% 
  filter(str_detect(text, "RC")) %>% 
  select(text)
```

```{r}
mystopwords <- tibble(word = c("eq", "co", "rc", "ac", "ak", "bn", 
                                   "fig", "file", "cg", "cb", "cm",
                               "ab"))

physics_words <- anti_join(physics_words, mystopwords, 
                           by = "word")

plot_physics <- physics_words %>%
  bind_tf_idf(word, author, n) %>%
  mutate(word = str_remove_all(word, "_")) %>%
  group_by(author) %>% 
  top_n(15, tf_idf) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, author)) %>%
  mutate(author = factor(author, levels = c("Galilei, Galileo",
                                            "Huygens, Christiaan",
                                            "Tesla, Nikola",
                                            "Einstein, Albert")))

ggplot(plot_physics, aes(word, tf_idf, fill = author)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~author, ncol = 2, scales = "free") +
  coord_flip() +
  scale_x_reordered()
```
# ngrams
```{r}
austen_books() %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2) ->
  austen_bigrams
austen_bigrams
```

```{r}
austen_bigrams %>%
  count(bigram, sort = TRUE)
```

```{r}
austen_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")->
  bigrams_separated

bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) ->
  bigrams_filtered

# new bigram counts:
bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)->
  bigram_counts

bigram_counts
```

```{r}
bigrams_filtered %>%
  unite(bigram, word1, word2, sep = " ")->
  bigrams_united

bigrams_united %>% 
  count(bigram, sort = TRUE)
```

```{r}
bigrams_filtered %>%
  filter(word2 == "street") %>%
  count(book, word1, sort = TRUE)
```

```{r}
#or 
bigrams_united %>% 
  filter(str_detect(bigram,"street")) %>% 
  count(book, bigram, sort = TRUE)
```

```{r}
 bigrams_united %>%
  count(book, bigram) %>%
  bind_tf_idf(bigram, book, n) %>%
  arrange(desc(tf_idf)) ->
  bigram_tf_idf

bigram_tf_idf
```

```{r}
bigram_tf_idf %>% 
  group_by(book) %>% 
  top_n(10, tf_idf) %>%
  ungroup() %>%
  mutate(bigram = reorder_within(bigram, tf_idf, book)) %>%
  ggplot(aes(bigram, tf_idf, fill = book)) +
    geom_col(show.legend = FALSE) +
    labs(x = NULL, y = "tf-idf") +
    facet_wrap(~book, ncol = 2, scales = "free") +
    coord_flip() +
    scale_x_reordered()
```

```{r}
bigrams_separated %>%
  filter(word1 == "not") %>%
  count(word1, word2, sort = TRUE)
```

```{r}
AFINN <- get_sentiments("afinn")
AFINN
```

```{r}
bigrams_separated %>%
  filter(word1 == "not") %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word2, value, sort = TRUE) ->
  not_words

not_words
```

```{r}
not_words %>%
  mutate(contribution = n * value) %>%
  arrange(desc(abs(contribution))) %>%
  head(20) %>%
  mutate(word2 = reorder(word2, contribution)) %>%
  ggplot(aes(word2, n * value, fill = n * value > 0)) +
  geom_col(show.legend = FALSE) +
  xlab("Words preceded by \"not\"") +
  ylab("Sentiment value * number of occurrences") +
  coord_flip()
```

```{r}
negation_words <- c("not", "no", "never", "without")

bigrams_separated %>%
  filter(word1 %in% negation_words) %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word1, word2, value, sort = TRUE) ->
  negated_words

negated_words %>%
  mutate(contribution = n * value) %>% 
  group_by(word1) %>% 
  top_n(12, abs(contribution)) %>%  
  ungroup()  %>% 
  ggplot(aes(reorder_within(word2,contribution, word1), n * value, 
             fill = n * value > 0)) +
    geom_col(show.legend = FALSE) +
    xlab("Words preceded by negation term") +
    ylab("Sentiment value * Number of Occurrences") +
    coord_flip() +
    facet_wrap(~word1, scales = "free") +
    scale_x_discrete(labels = function(x) str_replace(x,"__.+$", ""))
```

```{r}
library(igraph)
bigram_counts
```

```{r}
bigram_counts %>%
  filter(n > 20) %>%
  graph_from_data_frame()->
  bigram_graph

bigram_graph
```

```{r}
library(ggraph)
set.seed(17)

ggraph(bigram_graph, layout = "fr") + #The layout_with_fr() Fruchterman-Reingold layout
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)+ 
   theme_void()
```

```{r}
# With repel = TRUE
 ggraph(bigram_graph, layout = "fr") + # layout_with_fr() uses the 
   # Fruchterman-Reingold layout
  geom_edge_link() +
  #geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1, repel = TRUE) + 
   theme_void()
```

```{r}
library(tm)

data("AssociatedPress", package = "topicmodels")
AssociatedPress
```
```{r}
ap_td <- tidy(AssociatedPress)
ap_td
```

```{r}
 ap_td %>%
  inner_join(get_sentiments("bing"), by = c(term = "word"))->
  ap_sentiments 

ap_sentiments
```

```{r}
ap_sentiments %>%
  count(sentiment, term, wt = count) %>%
  ungroup() %>%
  filter(n >= 200) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(term = reorder(term, n)) %>%
  ggplot(aes(term, n, fill = sentiment)) +
  geom_bar(stat = "identity") +
  ylab("Contribution to sentiment") +
  coord_flip()
```


```{r}
data("data_corpus_inaugural", package = "quanteda")
inaug_dfm <- quanteda::dfm(data_corpus_inaugural, verbose = FALSE)
inaug_dfm
```

```{r}
inaug_td <- tidy(inaug_dfm)
inaug_td
```

```{r}
inaug_tf_idf <- inaug_td %>%
  bind_tf_idf(term, document, count) %>%
  arrange(desc(tf_idf))

inaug_tf_idf
```


```{r}
inaug_tf_idf %>% 
  filter(document %in% c("1861-Lincoln", "1933-Roosevelt","1961-Kennedy","2009-Obama")) %>% 
  mutate(term = str_extract(term, "[a-z']+")) %>%
  group_by(document) %>% 
  arrange(desc(tf-idf)) %>% 
  top_n(10) %>% 
  ungroup() %>% 
 
  ggplot(aes(x=reorder_within(term, tf_idf, document), 
             y=tf_idf, fill = document)) +
  geom_col(show.legend = FALSE)+
  facet_wrap(~document, scales = "free") +
  coord_flip() +
  scale_x_discrete(labels = function(x) str_replace(x,"__.+$", ""))
```



```{r}
ap_td %>%
  cast_dtm(document, term, count)
```


```{r}
ap_td %>%
  cast_dfm(document, term, count)
```

```{r}
data("acq")
acq
```

```{r}
acq_td <- tidy(acq)
acq_td
```

```{r}
acq_tokens <- acq_td %>%
  select(-places) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = "word")

# most common words
acq_tokens %>%
  count(word, sort = TRUE)
```

```{r}
# tf-idf
acq_tokens %>%
  count(id, word) %>%
  bind_tf_idf(word, id, n) %>%
  arrange(desc(tf_idf))
```

# Mapping

```{r}
unloadNamespace("tidytext")
unloadNamespace("ggraph")
unloadNamespace("tidygraph")
unloadNamespace("igraph")
unloadNamespace("tm")
unloadNamespace("gutenbergr")
unloadNamespace("NLP")
unloadNamespace("janeaustenr")
search()
```


```{r}
library(tidyverse)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(ggspatial)
library(sf)
library(lwgeom)

```

```{r}
theme_set(theme_bw())
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

ggplot(data = world) +
  geom_sf() +
xlab("Longitude") + ylab("Latitude") +
ggtitle("World map", 
        subtitle = paste0("(", length(unique(world$name)), " countries)"))
```

```{r}
ggplot(data = world) +
    geom_sf(aes(fill = pop_est)) +
    scale_fill_viridis_c(option = "plasma", trans = "sqrt")
```

```{r}
ggplot(data = world) +
    geom_sf() +
    coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.97), expand = FALSE)
```

```{r}
ggplot(data = world) +
    geom_sf(aes(fill = gdp_md_est)) +
    coord_sf(xlim = c(70, 150), ylim = c(15, 55), expand = FALSE) +
    scale_fill_viridis_c(option = "plasma", trans = "sqrt")
```

```{r}
world_points<- st_centroid(world)
world_points <- cbind(world, st_coordinates(st_centroid(world$geometry)))

ggplot(data = world) +
geom_sf() +
geom_text(data= world_points,aes(x=X, y=Y, label=name),
    color = "darkblue", fontface = "bold", check_overlap = FALSE) +
annotate(geom = "text", x = -90, y = 26, label = "Gulf of Mexico", 
    fontface = "italic", color = "grey22", size = 6) +
coord_sf(xlim = c(-97.15, -70.12), ylim = c(7.65, 30.97), expand = FALSE)
```

```{r}
ggplot(data = world) + 
  geom_sf(fill= "antiquewhite") + 
  geom_text(data= world_points,aes(x=X, y=Y, label=name), 
            color = "darkblue", fontface = "bold", check_overlap = FALSE) + 
  annotate(geom = "text", x = -90, y = 26, label = "Gulf of Mexico", 
           fontface = "italic", color = "grey22", size = 6) +
  annotation_scale(location = "bl", width_hint = 0.5) + 
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), 
                         style = north_arrow_fancy_orienteering) + 
  coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.97), expand = FALSE) +
  xlab("Longitude") + ylab("Latitude") + 
  ggtitle("Map of the Gulf of Mexico and the Caribbean Sea") + 
  theme(panel.grid.major = element_line(color = gray(.5), 
                                        linetype = "dashed", size = 0.5), 
        panel.background = element_rect(fill = "aliceblue"))
```
```{r}

sites <- data.frame(longitude = c(-80.144005, -80.109), latitude = c(26.479005, 
    26.83))
sites <- st_as_sf(sites, coords = c("longitude", "latitude"), 
    crs = 4326, agr = "constant")
```

```{r}
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)
```

```{r}
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-82, -78), ylim = c(24.5, 28), expand = FALSE)
```

```{r}
library(maps)
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states)
states <- cbind(states, st_coordinates(st_centroid(states)))
states$ID <- stringr::str_to_title(states$ID)
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) + 
    geom_text(data = states, aes(X, Y, label = ID), size = 5) +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)
```

```{r}
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties, grepl("florida", counties$ID))
counties$area <- as.numeric(st_area(counties))
head(counties)
```

```{r}
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = counties, aes(fill = area)) +
    scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)
```

```{r}
flcities <- data.frame(state = rep("Florida", 5), city = c("Miami", 
    "Tampa", "Orlando", "Jacksonville", "Sarasota"), lat = c(25.7616798, 
    27.950575, 28.5383355, 30.3321838, 27.3364347), lng = c(-80.1917902, 
    -82.4571776, -81.3792365, -81.655651, -82.5306527))

(flcities <- st_as_sf(flcities, coords = c("lng", "lat"), remove = FALSE, 
    crs = 4326, agr = "constant"))
```

```{r}
ggplot(data = world) +
geom_sf() +
geom_sf(data = counties, fill = NA, color = gray(.5)) +
geom_sf(data = flcities) +
geom_text(data = flcities, aes(x = lng, y = lat, label = city), 
    size = 3.9, col = "black", fontface = "bold") +
coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)
```

```{r}
library("ggrepel")
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = counties, fill = NA, color = gray(.5)) +
    geom_sf(data = flcities) +
    geom_text_repel(data = flcities, aes(x = lng, y = lat, label = city), 
        fontface = "bold", nudge_x = c(1, -1.5, 2, 2, -1), nudge_y = c(0.25, 
            -0.25, 0.5, 0.5, -0.5)) +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)
```

```{r}
states$nudge_y <- -1
states$nudge_y[states$ID == "Florida"] <- 1.1
states$nudge_y[states$ID == "South Carolina"] <- .1
ggplot(data = world) +
    geom_sf(fill = "antiquewhite1") +
    geom_sf(data = counties, aes(fill = area)) +
    geom_sf(data = states, fill = NA) + 
    geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
    geom_sf(data = flcities) +
    geom_text_repel(data = flcities, aes(x = lng, y = lat, label = city), 
        fontface = "bold", nudge_x = c(1, -1.5, 2, 2, -1), nudge_y = c(0.25, 
            -0.25, 0.5, 0.5, -0.5)) +
    geom_label(data = states, aes(X, Y, label = ID), size = 5, fontface = "bold", 
        nudge_y = states$nudge_y) +
    scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
    annotation_scale(location = "bl", width_hint = 0.4) +
    annotation_north_arrow(location = "bl", which_north = "true", 
        pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
        style = north_arrow_fancy_orienteering) +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE) +
    xlab("Longitude") + ylab("Latitude") +
    ggtitle("Observation Sites", subtitle = "(2 sites in Palm Beach County, Florida)") +
    theme(panel.grid.major = element_line(color = gray(0.5), linetype = "dashed", 
        size = 0.5), panel.background = element_rect(fill = "aliceblue"))
```

# usmap
```{r}
unloadNamespace("maps")
library(usmap)
data(statepop)
```

```{r}
states <- read_csv("./data/state_geo_data.csv", col_types = cols(OID = col_character()))
```
```{r}
url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"
df <- tibble(file_names = c("time_series_covid19_confirmed_US.csv",
                    "time_series_covid19_deaths_US.csv"))
df %>% 
  mutate(url = str_c(url_in, file_names, sep =""),
         data = map(url, ~read_csv(., col_types = cols(FIPS = col_factor()), na = "")),
         case_type = as.factor(str_extract(file_names,"[:alpha:]*_[gU][:alpha:]*"))) %>%
  select(case_type, data) ->
  df

 df$vars <- map(df$data,  names)
```

```{r}
#create a helper function
    fix_names <- function(df, pattern, repl){
     stopifnot(is.data.frame(df), is.character(pattern), is.character(repl))
      names(df) <- str_replace_all(names(df), pattern, repl)
      return(df)
    }
df %>% 
  mutate(data = map(data, ~ fix_names(., "Admin2", "County")),
         data = map(data, ~ fix_names(., "Long_", "Long")),
         data = map_if(data, !str_detect(df$case_type,"deaths_US"),
                       ~ mutate(., Population = 0)),
         data = map(data, ~filter(., !is.na(FIPS))),
         data = map(data, ~ mutate(., cFIPS = str_extract(UID,".{5}$"),
                                   sFIPS = str_extract(cFIPS, "^..")))
         )->df

df$vars <- map(df$data,  names)
```
```{r}
df %>% 
  mutate(data = map(data, ~ pivot_longer(data = ., cols = contains("/"), 
                                         names_to = "Date", 
                                         values_to = "Daily_Total") ))-> 
df

#helper function for Date Change
fix_date_mdy <- function(df,var_name){
  stopifnot(is.data.frame(df), is.character(var_name))
  df[[var_name]]<- mdy(df[[var_name]])
  return(df)
}
library(lubridate)
df %>%
  mutate(data = map(data, ~fix_date_mdy(., "Date")))-> 
df
```
```{r}

 df %>% 
  unnest(cols=data) %>% 
  ungroup() ->
  df_all
   # rm(df)
df_all <- select(df_all, -vars)
```

```{r}
df_all %>% 
  group_by(UID) %>% 
  filter(!is.na(cFIPS), County !="Unassigned", !str_detect(County, "^Out of ")) %>% 
  mutate(Population = max(Population),
         Daily_Total_percap = Daily_Total/Population)->
  df_all
#write_csv(df_all, "./data/covid_us_data.csv")
```

```{r}
plot_usmap(regions = "states") + 
  labs(title = "US States",
       subtitle = "This is a blank map of the states of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))
```

```{r}
plot_usmap(include = .south_atlantic, labels = TRUE) + 
  labs(title = "US South Atlantic States",
       subtitle = "This is a blank map of the states in the South Atlantic Census Region") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))
```
```{r}
plot_usmap(regions = "counties") + 
  labs(title = "US Counties",
       subtitle = "This is a blank map of the counties of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))
```

```{r}
plot_usmap("counties", include = c("VA", "MD", "DC")) +
  labs(title = "Custom DMV Area",
       subtitle = "These are the counties in MD, DC< anD VA.")+ 
  theme(panel.background = element_rect(color = "blue", fill = "lightblue"))
```

```{r}
dmv_county_fips <- c("11001","24003","24009","24017","24021","24027","24031",
                     "24033","51013","51059","51061","51107","51153","51179",
                     "51510","51600","51610","51630","51683","51685")
plot_usmap("counties", include = dmv_county_fips) +
  labs(title = "Greater DMV Area",
       subtitle = "These are the Counties/Cities in the Greater DMV area.")+ 
  theme(panel.background = element_rect(color = "blue", fill = "lightblue"))
```

```{r}
df_all %>% 
  filter(Date == max(Date), Population >0, !is.na(sFIPS)) %>% 
  group_by(sFIPS, case_type, Date) %>% 
  summarise(Current_Total = sum(Daily_Total),
            Current_Total_percap = sum(Daily_Total)/sum(Population))->
  state_totals
```

```{r}
state_totals %>% 
  filter(case_type =="confirmed_US") %>% 
  rename(fips = sFIPS)-> 
  state_cases
plot_usmap(data = state_cases, values = "Current_Total", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Confirmed Cases", label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Cases by State as of ", 
                         max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

```{r}
state_totals %>% 
  filter(case_type =="deaths_US") %>% 
  rename(fips = sFIPS)-> 
  state_cases
plot_usmap(data = state_cases, values = "Current_Total", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Total Deaths", label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Deaths by State as of ", max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

```{r}
state_totals %>% 
  filter(case_type =="deaths_US") %>% 
  rename(fips = sFIPS)-> 
  state_cases
plot_usmap(data = state_cases, values = "Current_Total", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Total Deaths", label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Deaths by State as of ", max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

```{r}
state_totals %>% 
  filter(case_type =="deaths_US") %>% 
  rename(fips = sFIPS)-> 
  state_cases
plot_usmap(data = state_cases, values = "Current_Total_percap", 
           color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Total Deaths Per Capita", 
                        label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Deaths per Capita by State as of ", 
                         ... = max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "right")
```

```{r}
state_totals %>% 
  filter(case_type =="deaths_US") %>% 
  mutate(Current_Total10 = log10(Current_Total),
         Current_Total_percap10 = log10(Current_Total_percap)) %>% 
  rename(fips = sFIPS)-> 
  state_cases
plot_usmap(data = state_cases, values = "Current_Total_percap10", 
           color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Total Deaths per Capita (Log 10)", 
                        label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Log(10) of Total Deaths per Capita by State as of ", 
                         ... = max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "right")
```

```{r}
state_cases %>% 
  left_join(states, by = c("fips"="STATE")) %>% 
  mutate(Current_Total_perarea = Current_Total/AREALAND)->
  state_casesa

plot_usmap(data = state_casesa, values = "Current_Total_perarea", 
           color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Total Deaths per unit Area (Log 10)", 
                        label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Deaths per unit area by State as of ", 
                         ... = max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "right")
```

```{r}
df_all %>% 
  filter(Date == max(Date), Population >0, !is.na(cFIPS)) %>% 
  group_by(cFIPS, case_type, Date) %>% 
  summarise(Current_Total = sum(Daily_Total),
            Current_Total_percap = sum(Daily_Total)/sum(Population))->
  county_totals

```
```{r}
county_totals %>% 
  filter(case_type =="confirmed_US") %>% 
  mutate(Current_Total_log2 = log2(Current_Total)) %>% 
  rename(fips = cFIPS)-> 
  county_cases
plot_usmap(data = county_cases, include = c("NY","NJ"),
           values = "Current_Total", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Confirmed Cases", label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Cases by County as of ", 
                         max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

```{r}
plot_usmap(data = county_cases, include = dmv_county_fips,
           values = "Current_Total", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Confirmed Cases", label = scales::comma)+
  labs(title = "DMV Region",
       subtitle = paste0("Total Cases by County/City as of ", 
                         max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

```{r}
county_totals %>% 
  filter(case_type =="deaths_US") %>% 
  rename(fips = cFIPS)-> 
  county_deaths
plot_usmap(data = county_deaths, include = dmv_county_fips,
           values = "Current_Total", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Confirmed Deaths", label = scales::comma)+
  labs(title = "DMV Region",
       subtitle = paste0("Total Deaths by County/City as of ", 
                         max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```
```{r}
plot_usmap(data = county_cases, include = dmv_county_fips,
           values = "Current_Total_percap", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Confirmed Cases Per Capita", label = scales::comma)+
  labs(title = "DMV Region",
       subtitle = paste0("Total Cases per Capita by County/City as of ", 
                         max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")

```

```{r}
county_totals %>% 
  filter(case_type =="deaths_US") %>% 
  rename(fips = cFIPS)-> 
  county_deaths
plot_usmap(data = county_deaths, include = dmv_county_fips,
           values = "Current_Total_percap", color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Confirmed Deaths per Capita", label = scales::comma)+
  labs(title = "DMV Region",
       subtitle = paste0("Total Deaths per Capita by County/City as of ", 
                         max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

# Census Data
```{r}
library(tidycensus)
library(tigris)
library(sf)
library(viridis) #a color palette
options(tigris_use_cache = TRUE)
```

```{r}
baltimore <- get_acs(state = "MD", county = "Baltimore City", geography = "tract", 
                  variables = "B19013_001", geometry = TRUE, key = Sys.getenv("CENSUS_API_KEY"))
#head(baltimore)
baltimore %>% 
ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  coord_sf(crs = 26911) + 
  scale_fill_viridis_c(option = "magma") 
```

```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")
baltimore_race <- get_decennial(state = "MD", county = "Baltimore City", 
                                geography = "tract", 
                                variables = racevars, geometry = TRUE, 
                                summary_var = "P001001",
                                key = Sys.getenv("CENSUS_API_KEY"))
```

```{r}
baltimore_race %>%
  mutate(pct = 100 * (value / summary_value)) %>%
  ggplot(aes(fill = pct)) +
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  coord_sf(crs = 26915) + 
  scale_fill_viridis_c()
```

```{r}
dc_median <- get_acs(state = "DC", county = "District of Columbia", geography = "tract", 
                  variables = "B19013_001", geometry = TRUE, key = Sys.getenv("CENSUS_API_KEY"))
dc_median %>% 
  mutate(CENSUS_TRACT = str_sub(GEOID,6,11)) ->
  dc_median
```

```{r}
dc_median %>% 
ggplot(aes(fill = estimate)) +
    geom_sf(aes(geometry = geometry),color = NA) +
    coord_sf(crs = 26915) + 
    scale_fill_viridis_c() 
```

```{r}
crime <- read_csv("./data/dc-crimes-search-results.csv", col_types = cols(DISTRICT = col_factor(),
                                                                         WARD = col_factor(),
                                                                         PSA = col_factor(),
                                                                         METHOD= col_factor(),
                                                                         CENSUS_TRACT = col_character()
                                                                         ))
```

```{r}
crime %>% 
  filter(METHOD != "others") %>% 
  group_by(CENSUS_TRACT, METHOD) %>%
  count() %>% 
  left_join(dc_median) %>%
  ggplot(aes(fill = n)) +
    geom_sf(aes(geometry = geometry),color = NA) +
    coord_sf(crs = 26915) + 
    scale_fill_viridis_c() +
    facet_wrap(~METHOD) 
```

```{r}
wards <- read_sf("./data/Ward_from_2012")
wards %>% 
  mutate(WARD = parse_factor(as.character(WARD))) ->
  wards
   # head(wards)

```
```{r}
crime %>% 
  filter(METHOD != "others") %>% 
  group_by(WARD, METHOD) %>%
  count() %>% 
  left_join(wards) %>% 
  ggplot(aes(fill = n)) +
    geom_sf(aes(geometry = geometry),color = NA) +
    coord_sf(crs = 26915) + 
    scale_fill_viridis_c() +
    facet_wrap(~METHOD) 
```
```{r}
crime %>% 
  select(CENSUS_TRACT, WARD) %>% 
  group_by(CENSUS_TRACT) %>% 
  unique() %>% 
  count() %>% 
  filter(n>1) %>% 
  arrange(desc(n))
```

```{r}
au_latlong <- data.frame(longitude = -77.0888, latitude = 38.9375)
au_latlong<- st_as_sf(au_latlong, coords = c("longitude", "latitude"), 
    crs = 4326, agr = "constant")
```

```{r}
crime %>% 
  filter(METHOD != "others") %>% 
  group_by(WARD, METHOD) %>%
  count() %>% 
  left_join(wards) %>% 
  ggplot(aes(fill = n)) +
    geom_sf(aes(geometry = geometry),color = NA) +
    coord_sf(crs = 26915) + 
    scale_fill_viridis_c() +
    facet_wrap(~METHOD) +
   geom_sf(data = au_latlong, size = 4, shape = 23, fill = "red")
```

```{r}
dc_median %>% 
ggplot(aes(fill = estimate)) +
    geom_sf(aes(geometry = geometry),color = NA) +
    coord_sf(crs = 26915) + 
    scale_fill_viridis_c() +
   geom_sf(data = au_latlong, size = 4, shape = 23, fill = "red")
```

